### ISSUE TITLE
build failure

### ISSUE THREAD

**Issue by tylerbrockgeek** [NeutrinoAPI/NeutrinoAPI-Java#1]
Clone the latest and `mvn test` results in errors. Does the build pass for anyone at all?

$ mvn test
[WARNING]
[WARNING] Some problems were encountered while building the effective settings
[WARNING] Expected root element 'settings' but found 'profiles' (position: START_TAG seen <profiles>... @1:10)  @ /Users/tyler/.m2/settings.xml, line 1, column 10
[WARNING]
[INFO] Scanning for projects...
[INFO]
[INFO] ----------------------< NeutrinoAPI:neutrino-api >----------------------
[INFO] Building NeutrinoAPI 3.4.0
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-enforcer-plugin:3.0.0-M2:enforce (enforce-versions) @ neutrino-api ---
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ neutrino-api ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory /private/var/tmp/java/NeutrinoAPI-Java/src/main/resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ neutrino-api ---
[INFO] Changes detected - recompiling the module!
[WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent!
[INFO] Compiling 74 source files to /private/var/tmp/java/NeutrinoAPI-Java/target/classes
[INFO] -------------------------------------------------------------
[WARNING] COMPILATION WARNING :
[INFO] -------------------------------------------------------------
[WARNING] /private/var/tmp/java/NeutrinoAPI-Java/src/main/java/com/neutrinoapi/sdk/APIHelper.java: /private/var/tmp/java/NeutrinoAPI-Java/src/main/java/com/neutrinoapi/sdk/APIHelper.java uses unchecked or unsafe operations.
[WARNING] /private/var/tmp/java/NeutrinoAPI-Java/src/main/java/com/neutrinoapi/sdk/APIHelper.java: Recompile with -Xlint:unchecked for details.
[INFO] 2 warnings
[INFO] -------------------------------------------------------------
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /private/var/tmp/java/NeutrinoAPI-Java/src/main/java/com/neutrinoapi/sdk/http/client/UnirestClient.java:[8,43] package com.mashape.unirest.http.exceptions does not exist
[ERROR] /private/var/tmp/java/NeutrinoAPI-Java/src/main/java/com/neutrinoapi/sdk/http/client/UnirestClient.java:[9,1] package com.mashape.unirest.http.options does not exist
[ERROR] /private/var/tmp/java/NeutrinoAPI-Java/src/main/java/com/neutrinoapi/sdk/http/client/UnirestClient.java:[10,32] package com.mashape.unirest.http does not exist
[ERROR] /private/var/tmp/java/NeutrinoAPI-Java/src/main/java/com/neutrinoapi/sdk/http/client/UnirestClient.java:[124,68] package com.mashape.unirest.http does not exist
[ERROR] /private/var/tmp/java/NeutrinoAPI-Java/src/main/java/com/neutrinoapi/sdk/http/client/UnirestClient.java:[125,98] cannot find symbol
  symbol:   class UnirestException
  location: class com.neutrinoapi.sdk.http.client.UnirestClient
[ERROR] /private/var/tmp/java/NeutrinoAPI-Java/src/main/java/com/neutrinoapi/sdk/http/client/UnirestClient.java:[147,72] package com.mashape.unirest.http does not exist
[ERROR] /private/var/tmp/java/NeutrinoAPI-Java/src/main/java/com/neutrinoapi/sdk/http/client/UnirestClient.java:[174,49] package com.mashape.unirest.request does not exist
[ERROR] /private/var/tmp/java/NeutrinoAPI-Java/src/main/java/com/neutrinoapi/sdk/http/client/UnirestClient.java:[218,46] package com.mashape.unirest.http does not exist
[ERROR] /private/var/tmp/java/NeutrinoAPI-Java/src/main/java/com/neutrinoapi/sdk/http/client/UnirestClient.java:[26,8] com.neutrinoapi.sdk.http.client.UnirestClient is not abstract and does not override abstract method head(java.lang.String,java.util.Map<java.lang.String,java.lang.String>,java.util.List<java.util.AbstractMap.SimpleEntry<java.lang.String,java.lang.Object>>) in com.neutrinoapi.sdk.http.client.HttpClient
[ERROR] /private/var/tmp/java/NeutrinoAPI-Java/src/main/java/com/neutrinoapi/sdk/http/client/UnirestClient.java:[52,9] cannot find symbol
  symbol:   variable Unirest
  location: class com.neutrinoapi.sdk.http.client.UnirestClient
[ERROR] /private/var/tmp/java/NeutrinoAPI-Java/src/main/java/com/neutrinoapi/sdk/http/client/UnirestClient.java:[61,36] package com.mashape.unirest.request does not exist
[ERROR] /private/var/tmp/java/NeutrinoAPI-Java/src/main/java/com/neutrinoapi/sdk/http/client/UnirestClient.java:[63,37] package com.mashape.unirest.http does not exist
[ERROR] /private/var/tmp/java/NeutrinoAPI-Java/src/main/java/com/neutrinoapi/sdk/http/client/UnirestClient.java:[66,17] cannot find symbol
  symbol:   class UnirestException
  location: class com.neutrinoapi.sdk.http.client.UnirestClient
[ERROR] /private/var/tmp/java/NeutrinoAPI-Java/src/main/java/com/neutrinoapi/sdk/http/client/UnirestClient.java:[77,36] package com.mashape.unirest.request does not exist
[ERROR] /private/var/tmp/java/NeutrinoAPI-Java/src/main/java/com/neutrinoapi/sdk/http/client/UnirestClient.java:[79,37] package com.mashape.unirest.http does not exist
[ERROR] /private/var/tmp/java/NeutrinoAPI-Java/src/main/java/com/neutrinoapi/sdk/http/client/UnirestClient.java:[82,17] cannot find symbol
  symbol:   class UnirestException
  location: class com.neutrinoapi.sdk.http.client.UnirestClient
[ERROR] /private/var/tmp/java/NeutrinoAPI-Java/src/main/java/com/neutrinoapi/sdk/http/client/UnirestClient.java:[92,36] package com.mashape.unirest.request does not exist
[ERROR] /private/var/tmp/java/NeutrinoAPI-Java/src/main/java/com/neutrinoapi/sdk/http/client/UnirestClient.java:[94,37] package com.mashape.unirest.http does not exist
[ERROR] /private/var/tmp/java/NeutrinoAPI-Java/src/main/java/com/neutrinoapi/sdk/http/client/UnirestClient.java:[97,17] cannot find symbol
  symbol:   class UnirestException
  location: class com.neutrinoapi.sdk.http.client.UnirestClient
[ERROR] /private/var/tmp/java/NeutrinoAPI-Java/src/main/java/com/neutrinoapi/sdk/http/client/UnirestClient.java:[107,36] package com.mashape.unirest.request does not exist
[ERROR] /private/var/tmp/java/NeutrinoAPI-Java/src/main/java/com/neutrinoapi/sdk/http/client/UnirestClient.java:[109,37] package com.mashape.unirest.http does not exist
[ERROR] /private/var/tmp/java/NeutrinoAPI-Java/src/main/java/com/neutrinoapi/sdk/http/client/UnirestClient.java:[112,17] cannot find symbol
  symbol:   class UnirestException
  location: class com.neutrinoapi.sdk.http.client.UnirestClient
[ERROR] /private/var/tmp/java/NeutrinoAPI-Java/src/main/java/com/neutrinoapi/sdk/http/client/UnirestClient.java:[176,33] package com.mashape.unirest.http does not exist
[ERROR] /private/var/tmp/java/NeutrinoAPI-Java/src/main/java/com/neutrinoapi/sdk/http/client/UnirestClient.java:[180,36] package com.mashape.unirest.request does not exist
[ERROR] /private/var/tmp/java/NeutrinoAPI-Java/src/main/java/com/neutrinoapi/sdk/http/client/UnirestClient.java:[181,50] package com.mashape.unirest.request does not exist
[ERROR] /private/var/tmp/java/NeutrinoAPI-Java/src/main/java/com/neutrinoapi/sdk/http/client/UnirestClient.java:[187,42] package com.mashape.unirest.request does not exist
[ERROR] /private/var/tmp/java/NeutrinoAPI-Java/src/main/java/com/neutrinoapi/sdk/http/client/UnirestClient.java:[222,48] package com.mashape.unirest.http does not exist
[ERROR] /private/var/tmp/java/NeutrinoAPI-Java/src/main/java/com/neutrinoapi/sdk/http/client/UnirestClient.java:[225,48] package com.mashape.unirest.http does not exist
[ERROR] /private/var/tmp/java/NeutrinoAPI-Java/src/main/java/com/neutrinoapi/sdk/http/client/UnirestClient.java:[228,48] package com.mashape.unirest.http does not exist
[ERROR] /private/var/tmp/java/NeutrinoAPI-Java/src/main/java/com/neutrinoapi/sdk/http/client/UnirestClient.java:[231,48] package com.mashape.unirest.http does not exist
[ERROR] /private/var/tmp/java/NeutrinoAPI-Java/src/main/java/com/neutrinoapi/sdk/http/client/UnirestClient.java:[234,48] package com.mashape.unirest.http does not exist
[INFO] 31 errors
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 14.104 s
[INFO] Finished at: 2019-03-13T00:09:49+08:00
[INFO] ------------------------------------------------------------------------

**Comment by NeutrinoAPI** [comment]
Hi tylerbrockgeek,

It looks like your missing the dependencies, try run "mvn install" first to download the dependencies.

Usually you can just open the project in your IDE that supports maven. Both Eclipse and NetBeans should work out-of-the-box just open the project and clean and build. The README show you exactly how to do this in Eclipse.

If your just looking to get up and running with our APIs, see: https://www.neutrinoapi.com/api/api-examples/

If you would like to generate your own SDKs, see: https://www.neutrinoapi.com/api/specification/
